import type { Metadata } from "next";
import "./globals.css";
import { NavigationProvider } from "@/lib/NavigationContext";

export const metadata: Metadata = {
  title: "Tomodex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NavigationProvider>
      <html lang="en">
        <body
          id='RootLayout'
          className={`antialiased`}
        >
          {children}
        </body>
      </html>
  </NavigationProvider>
  );
}
