import type { Metadata } from "next";
import "./globals.css";
import { NavigationProvider } from "@/lib/NavigationContext";
import { ToastProvider } from "@/components/toast/ToastContext";
import ToastContainer from "@/components/toast/ToastContainer";

export const metadata: Metadata = {
  title: "Tomodex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NavigationProvider>
      <html lang="en">
        <body id="RootLayout" className="antialiased">
          <ToastProvider>
            {children}
            <ToastContainer />
          </ToastProvider>
        </body>
      </html>
    </NavigationProvider>
  );
}